export enum MessageEnum {
  ACCOUNT_SUCCESSFULLY_CREATED = 'Account successfully created',
  INCORRECT_ACCOUNT_OR_PASSWORD = 'Incorrect account or password',
  INCORRECT_PASSWORD = 'Incorrect password',
  YOUR_ACCOUNT_HAS_BEEN_LOCKED = 'Your account has been locked',
  LOGGED_IN_SUCCESSFULLY = 'Logged in successfully',
  REFRESH_TOKEN_SUCCESSFULLY = ' Refresh token successfully',
  LOG_OUT_SUCCESSFULLY = 'Log out successfully',
  TOO_MANY_REQUEST_FROM_YOUR_IP = 'Too many requests from your IP. Please try again later.',
  ACCESS_DENIED = 'Access Denied.',
  NOT_AUTHORIZED = 'Not authorized.',
  GET_PROFILE_SUCCESSFULLY = 'Get profile successfully.',
  GET_ALL_USERS_SUCCESSFULLY = 'Get all users successfully.',
  UPDATE_USER_SUCCESSFULLY = 'Update user successfully.',
  GET_ALL_STAFFS_SUCCESSFULLY = 'Get all staffs successfully.',
  GET_STAFF_DETAIL_SUCCESSFULLY = 'Get staff detail successfully.',
  CREATE_STAFF_SUCCESSFULLY = 'Create staff info successfully.',
  UPDATE_STAFF_SUCCESSFULLY = 'Update staff info successfully.',
}
